### ISSUE TITLE
Patient card edit mode design changes

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#154]
Please make some changes thanks
The reason is so I can make more space to enter more information.
Have text size of the data be the same as before edit mode.
If click Esc on the keyboard, then trigger cancel.
Also for medical notes

![admin-note-edit](https://user-images.githubusercontent.com/5784065/95024585-cfd96c00-0638-11eb-9c44-7746c267991a.png)

**Comment by arslansajid** [comment]
I have opened a PR for this issue, please let me know what you think of it.
