### ISSUE TITLE
In table user_grid, is it necessary to store "moved":false and "static":false in the database?

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#155]
In table user_grid, is it necessary to store "moved":false and "static":false in the database?

{"w":3,"h":4,"x":0,"y":0,"i":"Patient","moved":false,"static":false}

**Comment by arslansajid** [comment]
This is the data we get from the layout library on resizing and drag events, so in my opinion, there's no harm in saving the data as it is. Instead of modifying data every time a drag and resize event takes place and then save it in the database.

**Comment by davidjhp** [comment]
It is best for me to have the database data size be as small as possible.  Is it possible to store only the important parts such as "w":3,"h":4,"x":0,"y":0,"i":"Patient", and not store unimportant parts such as "moved" and "static", in the database?

**Comment by arslansajid** [comment]
Yes, we can do that, but that is also an overhead. We will be reducing the size of the database but in turn, we will be doing useless calculations on every drag and resize event which can reduce the efficiency of our front end application.

**Comment by arslansajid** [comment]
Since we will be saving the layout data in the db only when the user press the save icon, we can remove these extra attributes.

**Comment by davidjhp** [comment]
ok

**Comment by arslansajid** [comment]
PR has been added for this issue.
Going to mark this closed.
