### ISSUE TITLE
http://localhost:3000/patient/3

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#158]
Address or remove hardcoded data

**Comment by arslansajid** [comment]
Need more explanation on this.

**Comment by davidjhp** [comment]
Patient #3 has only the following data in database:
insert into patient (id, client_id, firstname, middlename, lastname, created) values (3, 1, 'John', 'B', 'Jennings', date_add(current_date, interval -20 day));

But on the page it says gender is female etc

![er1](https://user-images.githubusercontent.com/5784065/95406960-9b7fdd00-08d0-11eb-8cae-7514f213c13d.png)

**Comment by arslansajid** [comment]
For the patient balance to show on the billing card, where can I get this data?

**Comment by arslansajid** [comment]
In the patient API, there is no data available for the next appointment. Attached is the screenshot
<img width="827" alt="Screenshot 2020-10-08 at 2 12 00 PM" src="https://user-images.githubusercontent.com/19395679/95438967-6e830700-0970-11eb-90ae-f3928d046d46.png">

**Comment by davidjhp** [comment]
Regarding balance, try to sum up the amounts shown in the card, like this:

![er-billing-total](https://user-images.githubusercontent.com/5784065/95533143-380cb280-0997-11eb-8b28-734ca4515b15.png)

**Comment by davidjhp** [comment]
Regarding next appointment, try to add a function with the following sql:
            select min(start_dt) start_dt
            from user_calendar
            where patient_id=${req.patient_id}
            and start_dt>now()

**Comment by davidjhp** [comment]
Regarding balance, try to add a function with the following sql:

```
            select sum(t.amount) amount
            from tran t
            where t.patient_id=1


```

**Comment by arslansajid** [comment]
> select min(start_dt) start_dt
>             from user_calendar
>             where patient_id=${req.patient_id}
>             and start_dt>now()

This SQL is only returning the start_dt of the upcoming appointment. How can I get the upcoming appointment name which has to be displayed on the card?

**Comment by davidjhp** [comment]
In the design document where is the upcoming appointment name?
https://bitbucket.org/davidjhp2/clinios_spec/src/master/doctor_portal/patient.png
![er1](https://user-images.githubusercontent.com/5784065/95604010-ec482080-0a0b-11eb-9338-bfebffdfb4c1.png)

**Comment by arslansajid** [comment]
Sorry for the misunderstanding caused by me I took it all wrong.
