### ISSUE TITLE
Patient cards - drag only from top of the card

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#160]
On the patient cards I am not able to left click the mouse to copy text from the body of the card, can we make dragging only from the header of the card?

**Comment by arslansajid** [comment]
I will have to investigate whether this is possible with the layout library we are using.

**Comment by arslansajid** [comment]
Fortunately, I was digging out the documentation of the layout library and found that the library supports drag handle support out of the box. Saved plenty of time and hassle :)
