### ISSUE TITLE
Patient card - long data

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#164]
1. If data is very long then truncate data on right and put "..." at end.
2. Later if mouse hovers over a value with "..." then temporarily display a Tooltip with full data.
For example in the Diagnoses and Requisitions box

**Comment by davidjhp** [comment]
In the patient requisitions card, I see the "..." but when the mouse hovers over the "..." then temporarily display a Tooltip with full data.
Like this http://localhost:3000/manage/accounting-search

**Comment by davidjhp** [comment]
Also add to card Documents Notes, Messages, and any other field that might have long data.

**Comment by arslansajid** [comment]
Following cards have been updated:
Patient
Diagnoses
Handouts
Form
Requisitions

**Comment by davidjhp** [comment]
Some truncation is needed here

![er1](https://user-images.githubusercontent.com/5784065/96392797-01425380-1172-11eb-9492-0bcceadbf787.png)
