### ISSUE TITLE
http://localhost:3000/patient/1000 - patient does not exist

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#165]
http://localhost:3000/patient/1000
If patient does not exist then print message patient does not exist and stop

**Comment by davidjhp** [comment]
Is it possible that when patient does not exist we can also stop all cards from being shown?

**Comment by arslansajid** [comment]
Yes, it is possible. I have fixed this in a way that the cards will only be shown if the patient exists in the database.
