### ISSUE TITLE
Tables add total of column

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#173]
On these tables show Total at the bottom as shown here https://material-ui.com/components/tables/
    http://localhost:3000/setup/report-finance
    http://localhost:3000/manage/accounting-search

![Screen Shot 2020-10-04 at 9 01 37 PM](https://user-images.githubusercontent.com/5784065/95039578-038eb300-0686-11eb-8206-9a7b414a400e.png)
![Screen Shot 2020-10-04 at 9 02 11 PM](https://user-images.githubusercontent.com/5784065/95039588-05f10d00-0686-11eb-9052-e75a9397c939.png)

**Comment by shimulH** [comment]
do I have to calculate the total from client side? or am I getting the total from server side?

**Comment by davidjhp** [comment]
Lets first try from client side.

**Comment by shimulH** [comment]
ok I am doing calculation from client

**Comment by shimulH** [comment]
Please review the issue
