### ISSUE TITLE
Two pages - Change field spacing

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#178]
On these pages
http://localhost:3000/manage/patient-search
http://localhost:3000/setup/integrations

Make the TextField component spacing be like this page http://localhost:3000/manage/accounting-search

![er1](https://user-images.githubusercontent.com/5784065/95280373-ae7baa00-0809-11eb-9624-9c9a24e0039e.png)

**Comment by shimulH** [comment]
done
