### ISSUE TITLE
total line format

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#184]
make total line formatting and alignment be the same as lines above
make text size exactly the same
put $ on same side

![95391896-b50f2d80-08ac-11eb-96d0-df6fb2134582](https://user-images.githubusercontent.com/5784065/95392307-601fe700-08ad-11eb-95c8-bb7826495170.png)

**Comment by shimulH** [comment]
I am not getting any data after pulling last master branch, It is hard for me to predict the changes without data

**Comment by davidjhp** [comment]
I have the latest code from master branch, and I am getting data.  Ask Arslun if he can see the data?  Can you debug why there is no data?
