### ISSUE TITLE
Topbar patient search - message Nothing Found

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#190]
When I search for patients it says "Nothing Found" very quickly.
Can that message be not displayed when there actually are or will be results?

![Screen Shot 2020-10-08 at 5 01 39 PM](https://user-images.githubusercontent.com/5784065/95525460-0a207180-0989-11eb-8501-673a5cb96842.png)

**Comment by avastamin** [comment]
![Uploading topbar_search.gif…]()
