### ISSUE TITLE
Lets make the row padding consistent in all cards.

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#196]
Lets make the row padding consistent in all cards.
Maybe this can be defined in one place.

![er1](https://user-images.githubusercontent.com/5784065/95685088-9bbaf980-0baa-11eb-8c30-4d9abf8df3d2.png)

**Comment by arslansajid** [comment]
In encounters card, there is no spacing between the notes label and notes text, same is the case with the payment-plan label and payment-plan text
