### ISSUE TITLE
Encounters card looks different than the design

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#200]

**Comment by arslansajid** [comment]
Referring to the design: In encounters card, there is no spacing between the notes label and notes text and the same is the case with the payment-plan label and payment-plan text.
<img width="626" alt="Screenshot 2020-10-14 at 10 30 32 AM" src="https://user-images.githubusercontent.com/19395679/95947552-51cf4f00-0e08-11eb-9c32-f204d0cc316f.png">

**Comment by davidjhp** [comment]
The spacing is fine, I was referring to the database columns notes and treatment.

Here is better sql:

select e.dt, e.title, et.name encounter_type, concat(u.firstname, ' ', u.lastname) name, notes, treatment
from encounter e
left join encounter_type et on et.id=e.type_id
left join user u on u.id=e.user_id
where e.patient_id=1
