### ISSUE TITLE
Documents card, lets add the tabs All  Labs  Imaging  Uncategorized  Deleted

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#203]
Documents card, lets add the tabs All  Labs  Imaging  Uncategorized  Deleted
Also I created new logic for them in project.txt

**Comment by arslansajid** [comment]
Do we need these tabs inside the Document's card?

**Comment by davidjhp** [comment]
Would there be any problems in doing so?

**Comment by arslansajid** [comment]
Not at all sir, I have added these already.
<img width="762" alt="Screenshot 2020-10-14 at 10 37 39 AM" src="https://user-images.githubusercontent.com/19395679/95948079-4f212980-0e09-11eb-84b9-beb1e673af90.png">

**Comment by davidjhp** [comment]
Can those tabs be much smaller like the design?

**Comment by arslansajid** [comment]
That's how the tabs look after making them small.
<img width="763" alt="Screenshot 2020-10-15 at 11 00 09 AM" src="https://user-images.githubusercontent.com/19395679/96082991-b9070500-0ed5-11eb-8dd1-df24e35bbed9.png">

**Comment by davidjhp** [comment]
Can we use simple text instead that will work similarly to tabs?

**Comment by arslansajid** [comment]
Yes sir we can do that for sure.

**Comment by arslansajid** [comment]
This is the implementation of the text being used as tabs. I have made font-weight: bold for the selected tab for better user experience. Please let me know your thoughts on this.
<img width="763" alt="Screenshot 2020-10-15 at 9 00 18 PM" src="https://user-images.githubusercontent.com/19395679/96156226-46744480-0f2a-11eb-8966-5d4c95e52b5d.png">

**Comment by davidjhp** [comment]
Yes great

**Comment by arslansajid** [comment]
Perfect 👍
