### ISSUE TITLE
Tabs hide rows javascript

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#235]
When I click on tabs All Labs Imaging Uncategorized etc currently there is new SQL going to the database.  What is your opinion of using Javascript instead of SQL to hide/unhide the rows?

**Comment by arslansajid** [comment]
The solution to this is pretty straightforward. The backend should return all the records present in the database and we will filter them out on the basis of the "type" column in the document's table on the front end.

**Comment by davidjhp** [comment]
Yes lets do that
