### ISSUE TITLE
Documents card - add undelete icon

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#249]
Sometimes doctors might want to undelete a document that they previously deleted.
Documents card, tab Deleted, column Actions, show restore icon.
sql: update lab set status='A' where id=$id

**Comment by arslansajid** [comment]
I will add this functionality soon.

**Comment by davidjhp** [comment]
I deleted a document, then went to the Labs tab, and it was there.   Deleted documents should not be on tabs Labs Imaging Uncategorized.  Deleted documents should only be shown on tab Deleted.

**Comment by davidjhp** [comment]
Also when deleted please set lab.deleted_dt to todays date.  If undeleted set to lab.deleted_dt to null.

**Comment by arslansajid** [comment]
Fixed it.
