### ISSUE TITLE
Patient page duplicated sql

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#252]
When patient page loads, SQL statements are being run two times on the database.  Why two times?
For example see "from patient_allergy pa"

[patient-sql.txt](https://github.com/Clinios/clinios/files/5426636/patient-sql.txt)

**Comment by arslansajid** [comment]
@avastamin when the patient page these are the api calls are being sent. Since no duplicate API calls are called on the patient's page, could you please investigate why SQL statements are being run two times on the database? Attached is the screenshot of the browser's network tab.
Thanks!
<img width="1313" alt="Screenshot 2020-10-23 at 7 41 03 AM" src="https://user-images.githubusercontent.com/19395679/96951412-e1aa8280-1505-11eb-9612-4c4672132297.png">

**Comment by davidjhp** [comment]
I see the double SQLs in the server console log attached.

![Uploading er1.png…]()

**Comment by avastamin** [comment]
```
  useEffect(() => {
    if (!hasPatientIderror) {
      fetchPatientHistory();
      fetchPatientBalance();
      fetchAdminNotesHistory();
      fetchAllergies();
      fetchPatientHandouts();
      fetchForms();
      fetchBillings();
      fetchDocuments();
      fetchEncounters();
      fetchMedicalNotes();
      fetchMessages();
      fetchDiagnoses();
      fetchMedications();
      fetchRequisitions();
      fetchTests();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hasPatientIderror]);
```
I noticed these code as duplicate while you already have similar code on line:

```
useEffect(() => {
    if (!hasPatientIderror) {
      fetchPatientHistory();
      fetchPatientBalance();
      fetchAdminNotesHistory();
      fetchAllergies();
      fetchPatientHandouts();
      fetchForms();
      fetchBillings();
      fetchDocuments();
      fetchEncounters();
      fetchMedicalNotes();
      fetchMessages();
      fetchDiagnoses();
      fetchMedications();
      fetchRequisitions();
      fetchTests();
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }
  }, [
    hasPatientIderror,
    fetchPatientHistory,
    fetchPatientBalance,
    fetchAdminNotesHistory,
    fetchAllergies,
    fetchPatientHandouts,
    fetchForms,
    fetchBillings,
    fetchDocuments,
    fetchEncounters,
    fetchMedicalNotes,
    fetchMessages,
    fetchDiagnoses,
    fetchMedications,
    fetchRequisitions,
    fetchTests
  ]);
```

These scenario actually makes duplicate API calls so I removed the first code block. I recommend @arslansajid  to review this and test your patient page as you worked on this page and you know every bit of functionality of this page.

**Comment by avastamin** [comment]
I already removed those code and merged with master branch.

**Comment by arslansajid** [comment]
This seems to be the issue and now the issue has been fixed. I think this block was a result of the conflict that was produced during the eslint fixes. The patient page works perfectly after removing this block! Thanks for debugging this issue @avastamin, much appreciated.

**Comment by arslansajid** [comment]
Since the issue has been resolved, going to mark this issue as closed.
