### ISSUE TITLE
All pages with a modal to create new rows - prevent duplicate rows.

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#26]
On all pages that have a modal to create a new row, prevent the user from entering a duplicate row.
For example, on the Appointment Types page, prevent the user from creating a duplicate Appointment Type or a duplicate Appointment Type Portal Name.
Lets do this validation only on the frontend.
Use the error prop to toggle the error state, and the helperText prop to explain there is an issue, like the screenshot.
Because when we notify the user of an error, I prefer that the form does not move.

<img width="876" alt="validatation" src="https://user-images.githubusercontent.com/5784065/94827623-83362c80-03bd-11eb-8b65-5884eebfc2de.png">

**Comment by davidjhp** [comment]
http://localhost:3000/setup/appointment-types
I tried creating a duplicate type Initial appointment 1 hour and it is not working

**Comment by shimulH** [comment]
I tested ok, can you explain more
