### ISSUE TITLE
patient.png, upper left click monitor icon to go to patient portal for that patient id,

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#344]
project.txt line 1548
patient.png, upper left click monitor icon to go to patient portal for that patient id, automatically login to patient portal with no password.

**Comment by avastamin** [comment]
Requirements seems complicated to me. Here is my thought process:
1. patient.png is accessible as CLIENT
2. patient_portal is accessible as PATIENT

Possible solution 1:
When CLIENT click on that monitor icon:
i. CLIENT will be logged out and logged in as PATIENT with following id

Possible solution 2:
 User will be still logged in as CLIENT but able to see patient_portal for that specific patient.

Solution 2, seems promising to me. Let me know your opinion @davidjhp

**Comment by davidjhp** [comment]
Solution 2 seems good
